from __future__ import annotations

from decimal import Decimal
from pathlib import Path
import sys

from sqlalchemy import select


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from db.engine import session_scope
from db.models import Signal
from services.data_loader import load_price_data
from strategy_engine.ma_cross import generate_signal


def persist_latest_signal(signal_df) -> tuple[bool, Signal]:
    latest_row = signal_df.iloc[-1]
    latest_signal = int(latest_row["signal"])

    signal_record = Signal(
        symbol="NVDA",
        strategy_name="ma_cross",
        signal_type="BUY" if latest_signal == 1 else "SELL",
        signal_strength=Decimal(str(latest_signal)),
        timestamp=latest_row["timestamp"].to_pydatetime(),
        status="new",
        notes="Generated by 5/20 MA crossover strategy",
    )

    with session_scope() as session:
        existing = session.execute(
            select(Signal).where(
                Signal.symbol == signal_record.symbol,
                Signal.strategy_name == signal_record.strategy_name,
                Signal.timestamp == signal_record.timestamp,
            )
        ).scalar_one_or_none()

        if existing is not None:
            return False, existing

        session.add(signal_record)
        session.flush()
        return True, signal_record


def main() -> None:
    df = load_price_data("NVDA")
    signal_df = generate_signal(df)
    inserted, latest_record = persist_latest_signal(signal_df)

    print(f"Total row count: {len(signal_df)}")
    print(f"Columns: {list(signal_df.columns)}")
    print("Last 10 rows:")
    print(signal_df.tail(10).to_string(index=False))
    print(f"Latest signal value: {signal_df.iloc[-1]['signal']}")
    print(f"Inserted new signal row: {inserted}")
    print("Latest signal record:")
    print(
        {
            "symbol": latest_record.symbol,
            "strategy_name": latest_record.strategy_name,
            "signal_type": latest_record.signal_type,
            "signal_strength": latest_record.signal_strength,
            "timestamp": latest_record.timestamp,
            "status": latest_record.status,
            "notes": latest_record.notes,
        }
    )


if __name__ == "__main__":
    main()
